"""allow_multiple_game_sessions_per_room

Revision ID: 11508c81f7a5
Revises: c12ee0be6b5a
Create Date: 2026-08-10 21:23:07.669290

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11508c81f7a5"
down_revision: str | Sequence[str] | None = "c12ee0be6b5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_game_sessions_room_id"), "game_sessions", type_="unique"
    )
    op.create_index(
        op.f("ix_game_sessions_room_id"), "game_sessions", ["room_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_sessions_room_id"), table_name="game_sessions")
    op.create_unique_constraint(
        op.f("uq_game_sessions_room_id"),
        "game_sessions",
        ["room_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
