"""add participant removal timestamp

Revision ID: 39cd345b002c
Revises: 36e452490ec4
Create Date: 2026-08-10 06:43:15.452682

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39cd345b002c"
down_revision: str | Sequence[str] | None = "36e452490ec4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participants",
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_participants_removed_at"), "participants", ["removed_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_participants_removed_at"), table_name="participants")
    op.drop_column("participants", "removed_at")
    # ### end Alembic commands ###
