"""add participant answers

Revision ID: 5d4b90ea8295
Revises: 9f0476682643
Create Date: 2026-08-09 13:40:59.278409

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d4b90ea8295"
down_revision: str | Sequence[str] | None = "9f0476682643"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participant_answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_session_id", sa.UUID(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("quiz_question_id", sa.UUID(), nullable=False),
        sa.Column("selected_option_id", sa.UUID(), nullable=False),
        sa.Column(
            "is_correct", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "points_awarded", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "points_awarded >= 0",
            name=op.f(
                "ck_participant_answers_participant_answer_points_awarded_non_negative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game_sessions.id"],
            name=op.f("fk_participant_answers_game_session_id_game_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_participant_answers_participant_id_participants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_question_id"],
            ["quiz_questions.id"],
            name=op.f("fk_participant_answers_quiz_question_id_quiz_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["selected_option_id"],
            ["quiz_answer_options.id"],
            name=op.f("fk_participant_answers_selected_option_id_quiz_answer_options"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participant_answers")),
        sa.UniqueConstraint(
            "game_session_id",
            "participant_id",
            "quiz_question_id",
            name="participant_answer_session_participant_question_unique",
        ),
    )
    op.create_index(
        op.f("ix_participant_answers_game_session_id"),
        "participant_answers",
        ["game_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participant_answers_participant_id"),
        "participant_answers",
        ["participant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participant_answers_quiz_question_id"),
        "participant_answers",
        ["quiz_question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_participant_answers_quiz_question_id"),
        table_name="participant_answers",
    )
    op.drop_index(
        op.f("ix_participant_answers_participant_id"), table_name="participant_answers"
    )
    op.drop_index(
        op.f("ix_participant_answers_game_session_id"), table_name="participant_answers"
    )
    op.drop_table("participant_answers")
    # ### end Alembic commands ###
