"""add quiz templates and game sessions

Revision ID: 9f0476682643
Revises: c8cc8d0cf826
Create Date: 2026-08-08 22:59:54.416779

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f0476682643"
down_revision: str | Sequence[str] | None = "c8cc8d0cf826"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_published",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_templates")),
        sa.UniqueConstraint("title", name=op.f("uq_quiz_templates_title")),
    )
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column(
            "game_type",
            sa.String(length=40),
            server_default=sa.text("'quiz'"),
            nullable=False,
        ),
        sa.Column("quiz_template_id", sa.UUID(), nullable=True),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_template_id"],
            ["quiz_templates.id"],
            name=op.f("fk_game_sessions_quiz_template_id_quiz_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_game_sessions_room_id_rooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_sessions")),
        sa.UniqueConstraint("room_id", name=op.f("uq_game_sessions_room_id")),
    )
    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quiz_template_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "time_limit_seconds",
            sa.Integer(),
            server_default=sa.text("30"),
            nullable=False,
        ),
        sa.Column(
            "points", sa.Integer(), server_default=sa.text("100"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "points > 0", name=op.f("ck_quiz_questions_quiz_question_points_positive")
        ),
        sa.CheckConstraint(
            "time_limit_seconds > 0",
            name=op.f("ck_quiz_questions_quiz_question_time_limit_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["quiz_template_id"],
            ["quiz_templates.id"],
            name=op.f("fk_quiz_questions_quiz_template_id_quiz_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
        sa.UniqueConstraint(
            "quiz_template_id",
            "position",
            name="quiz_question_template_position_unique",
        ),
    )
    op.create_index(
        op.f("ix_quiz_questions_quiz_template_id"),
        "quiz_questions",
        ["quiz_template_id"],
        unique=False,
    )
    op.create_table(
        "quiz_answer_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quiz_question_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "is_correct", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quiz_question_id"],
            ["quiz_questions.id"],
            name=op.f("fk_quiz_answer_options_quiz_question_id_quiz_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_answer_options")),
        sa.UniqueConstraint(
            "quiz_question_id", "position", name="quiz_option_question_position_unique"
        ),
    )
    op.create_index(
        op.f("ix_quiz_answer_options_quiz_question_id"),
        "quiz_answer_options",
        ["quiz_question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quiz_answer_options_quiz_question_id"),
        table_name="quiz_answer_options",
    )
    op.drop_table("quiz_answer_options")
    op.drop_index(
        op.f("ix_quiz_questions_quiz_template_id"), table_name="quiz_questions"
    )
    op.drop_table("quiz_questions")
    op.drop_table("game_sessions")
    op.drop_table("quiz_templates")
    # ### end Alembic commands ###
