"""align participant answer points check constraint

Revision ID: b7fd1d43ef96
Revises: 5d4b90ea8295
Create Date: 2026-08-09 13:47:09.887057

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7fd1d43ef96"
down_revision: str | Sequence[str] | None = "5d4b90ea8295"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_participant_answers_participant_answer_points_awarde_718c"),
        "participant_answers",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_participant_answers_participant_answer_points_awarded_non_negative"),
        "participant_answers",
        "points_awarded >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_participant_answers_participant_answer_points_awarded_non_negative"),
        "participant_answers",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_participant_answers_participant_answer_points_awarde_718c"),
        "participant_answers",
        "points_awarded >= 0",
    )
    # ### end Alembic commands ###
