"""allow_rejoin_after_participant_removal

Revision ID: c12ee0be6b5a
Revises: 39cd345b002c
Create Date: 2026-08-10 19:41:55.673783

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c12ee0be6b5a"
down_revision: str | Sequence[str] | None = "39cd345b002c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("participant_room_username_unique"), "participants", type_="unique"
    )
    op.create_index(
        "participant_active_room_username_unique",
        "participants",
        ["room_id", "username_normalized"],
        unique=True,
        postgresql_where=sa.text("removed_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "participant_active_room_username_unique",
        table_name="participants",
    )
    op.create_unique_constraint(
        op.f("participant_room_username_unique"),
        "participants",
        ["room_id", "username_normalized"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
