"""create participants table

Revision ID: c8cc8d0cf826
Revises: 0fa828e31374
Create Date: 2026-08-08 05:46:16.565917

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8cc8d0cf826"
down_revision: str | Sequence[str] | None = "0fa828e31374"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("username_normalized", sa.String(length=40), nullable=False),
        sa.Column("participant_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_participants_room_id_rooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
        sa.UniqueConstraint(
            "room_id", "username_normalized", name="participant_room_username_unique"
        ),
    )
    op.create_index(
        op.f("ix_participants_room_id"), "participants", ["room_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_participants_room_id"), table_name="participants")
    op.drop_table("participants")
    # ### end Alembic commands ###
